version: "3.3"
services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    environment:
      - MYSQL_HOST=db
    depends_on:
      - db
  db:
    image: mysql:8
    ports:
      - 3309:3306
    volumes:
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=lucid
      - MYSQL_USER=lucid
      - MYSQL_PASSWORD=test123
      - MYSQL_ROOT_PASSWORD=test123
volumes:
  db-store:
